//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostITT
{
    using System;
    using System.Collections.Generic;
    
    public partial class POST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POST()
        {
            this.MEDIA = new HashSet<Medium>();
            this.POST1 = new HashSet<POST>();
            this.RANKs = new HashSet<RANK>();
        }
    
        public short POSTID { get; set; }
        public Nullable<short> PARENTID { get; set; }
        public Nullable<System.DateTime> POSTDATE { get; set; }
        public string POSTTEXT { get; set; }
        public Nullable<short> USERID { get; set; }
        public Nullable<short> POSTTYPEID { get; set; }
        public Nullable<short> CATEGORYID { get; set; }
        public Nullable<short> MEDIAID { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual ITTUSER ITTUSER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medium> MEDIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POST> POST1 { get; set; }
        public virtual POST POST2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RANK> RANKs { get; set; }
        public virtual POSTTYPE POSTTYPE { get; set; }
    }
}
