//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostITT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PostITTEntities : DbContext
    {
        public PostITTEntities()
            : base("name=PostITTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATEGORY> CATEGORies { get; set; }
        public virtual DbSet<ITTUSER> ITTUSERs { get; set; }
        public virtual DbSet<Medium> MEDIA { get; set; }
        public virtual DbSet<MEDIATYPE> MEDIATYPEs { get; set; }
        public virtual DbSet<POST> POSTs { get; set; }
        public virtual DbSet<POSTTYPE> POSTTYPEs { get; set; }
        public virtual DbSet<RANK> RANKs { get; set; }
        public virtual DbSet<TAG> TAGs { get; set; }
        public virtual DbSet<USERTYPE> USERTYPEs { get; set; }
        public virtual DbSet<MEDIA_MODERATOR_VIEW> MEDIA_MODERATOR_VIEW { get; set; }
        public virtual DbSet<VIEWPOST> VIEWPOSTS { get; set; }
        public virtual DbSet<VIEWUSER> VIEWUSERs { get; set; }
        public virtual DbSet<VIEWUSERPOST> VIEWUSERPOSTS { get; set; }
        public virtual DbSet<VIEWUSERPOSTSTYPECATTAGRANK> VIEWUSERPOSTSTYPECATTAGRANKs { get; set; }
        public virtual DbSet<VIEWUSERPROFILE> VIEWUSERPROFILEs { get; set; }
        public virtual DbSet<VIEWUSERTYPEPOST> VIEWUSERTYPEPOSTS { get; set; }
    
        public virtual int ANSWERPOST()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ANSWERPOST");
        }
    
        public virtual int CREATEADMINISTRATOR()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CREATEADMINISTRATOR");
        }
    
        public virtual int CREATECATEGORY(string cATDESC)
        {
            var cATDESCParameter = cATDESC != null ?
                new ObjectParameter("CATDESC", cATDESC) :
                new ObjectParameter("CATDESC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CREATECATEGORY", cATDESCParameter);
        }
    
        public virtual int CREATEITTUSER(string fIRSTNAME, string sURNAME, string pASSWORD, string eMAIL)
        {
            var fIRSTNAMEParameter = fIRSTNAME != null ?
                new ObjectParameter("FIRSTNAME", fIRSTNAME) :
                new ObjectParameter("FIRSTNAME", typeof(string));
    
            var sURNAMEParameter = sURNAME != null ?
                new ObjectParameter("SURNAME", sURNAME) :
                new ObjectParameter("SURNAME", typeof(string));
    
            var pASSWORDParameter = pASSWORD != null ?
                new ObjectParameter("PASSWORD", pASSWORD) :
                new ObjectParameter("PASSWORD", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CREATEITTUSER", fIRSTNAMEParameter, sURNAMEParameter, pASSWORDParameter, eMAILParameter);
        }
    
        public virtual int CREATETAG(string tAGDESC, Nullable<decimal> cATID)
        {
            var tAGDESCParameter = tAGDESC != null ?
                new ObjectParameter("TAGDESC", tAGDESC) :
                new ObjectParameter("TAGDESC", typeof(string));
    
            var cATIDParameter = cATID.HasValue ?
                new ObjectParameter("CATID", cATID) :
                new ObjectParameter("CATID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CREATETAG", tAGDESCParameter, cATIDParameter);
        }
    
        public virtual int CREATEUSERTYPE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CREATEUSERTYPE");
        }
    
        public virtual int DEREGISTERITTUSER(string fNAM, string sNAM, string pASS)
        {
            var fNAMParameter = fNAM != null ?
                new ObjectParameter("FNAM", fNAM) :
                new ObjectParameter("FNAM", typeof(string));
    
            var sNAMParameter = sNAM != null ?
                new ObjectParameter("SNAM", sNAM) :
                new ObjectParameter("SNAM", typeof(string));
    
            var pASSParameter = pASS != null ?
                new ObjectParameter("PASS", pASS) :
                new ObjectParameter("PASS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DEREGISTERITTUSER", fNAMParameter, sNAMParameter, pASSParameter);
        }
    
        public virtual int INFORMATIVEPOST()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INFORMATIVEPOST");
        }
    
        public virtual int INITIALPOST(string pOSTID)
        {
            var pOSTIDParameter = pOSTID != null ?
                new ObjectParameter("POSTID", pOSTID) :
                new ObjectParameter("POSTID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INITIALPOST", pOSTIDParameter);
        }
    
        public virtual int LOADAFILEPROCEDURE(string dIR_NAME, string uRL)
        {
            var dIR_NAMEParameter = dIR_NAME != null ?
                new ObjectParameter("DIR_NAME", dIR_NAME) :
                new ObjectParameter("DIR_NAME", typeof(string));
    
            var uRLParameter = uRL != null ?
                new ObjectParameter("URL", uRL) :
                new ObjectParameter("URL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LOADAFILEPROCEDURE", dIR_NAMEParameter, uRLParameter);
        }
    
        public virtual int LOGIN(string v_EMAIL, string v_PASSWORD)
        {
            var v_EMAILParameter = v_EMAIL != null ?
                new ObjectParameter("V_EMAIL", v_EMAIL) :
                new ObjectParameter("V_EMAIL", typeof(string));
    
            var v_PASSWORDParameter = v_PASSWORD != null ?
                new ObjectParameter("V_PASSWORD", v_PASSWORD) :
                new ObjectParameter("V_PASSWORD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LOGIN", v_EMAILParameter, v_PASSWORDParameter);
        }
    
        public virtual int QUESTIONPOST()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("QUESTIONPOST");
        }
    
        public virtual int REPLYPOST()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("REPLYPOST");
        }
    
        public virtual int REPLYPOSTPROC(Nullable<decimal> cHILDPOSTID, Nullable<decimal> pARENTPOSTID)
        {
            var cHILDPOSTIDParameter = cHILDPOSTID.HasValue ?
                new ObjectParameter("CHILDPOSTID", cHILDPOSTID) :
                new ObjectParameter("CHILDPOSTID", typeof(decimal));
    
            var pARENTPOSTIDParameter = pARENTPOSTID.HasValue ?
                new ObjectParameter("PARENTPOSTID", pARENTPOSTID) :
                new ObjectParameter("PARENTPOSTID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("REPLYPOSTPROC", cHILDPOSTIDParameter, pARENTPOSTIDParameter);
        }
    
        public virtual int UPDATESCORE(Nullable<decimal> uID)
        {
            var uIDParameter = uID.HasValue ?
                new ObjectParameter("UID", uID) :
                new ObjectParameter("UID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATESCORE", uIDParameter);
        }
    }
}
