//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostITT
{
    using System;
    using System.Collections.Generic;
    
    public partial class RANK
    {
        public short RANKID { get; set; }
        public short POSTRANK { get; set; }
        public short USERID { get; set; }
        public Nullable<short> POSTID { get; set; }
    
        public virtual ITTUSER ITTUSER { get; set; }
        public virtual POST POST { get; set; }
    }
}
